
when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      bind:
        Symfony\Component\HttpKernel\KernelInterface: '@kernel'

    App\Tests\Behat\Context\:
      resource: '%kernel.project_dir%/tests/Behat/Context'
