monolog:
  channels:
    - deprecation

when@prod:
  monolog:
    handlers:
      stderr:
        type: stream
        path: php://stderr
        level: error
        formatter: monolog.formatter.line

when@dev: &dev
  monolog:
    handlers:
      stderr:
        type: stream
        path: php://stderr
        formatter: monolog.formatter.line
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine", "!console" ]

when@test: *dev

