services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\Persistence\Doctrine\Repository\:
    resource: '%kernel.project_dir%/app/Infrastructure/Persistence/Doctrine/Repository/'
