
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Blog\Domain\Content\ArticleContentRendererInterface:
    class: App\Blog\Infrastructure\Content\ContentRenderer\MarkdownArticleContentRenderer
