
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Blog\Domain\Content\ArticlePreviewGeneratorInterface:
    class: App\Blog\Infrastructure\Content\PreviewGenerator\SimpleHtmlContentBasedPreviewGenerator
