
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Blog\Domain\ArticleSlugGeneratorInterface:
    class: App\Blog\Infrastructure\Slug\ArticleSlugGenerator

  App\Blog\Domain\Category\CategorySlugGeneratorInterface:
    class: App\Blog\Infrastructure\Slug\CategorySlugGenerator
