
parameters:
  env(GITHUB_WEBHOOK_SECRET): 'webhook_secret_value'

  app.github.webhook.secret: '%env(GITHUB_WEBHOOK_SECRET)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Github\HttpClient\Builder:
    arguments:
      - '@psr18.http_client'
      - '@psr18.http_client'
      - '@psr18.http_client'

  Github\Client:
    arguments:
      $httpClientBuilder: '@Github\HttpClient\Builder'
  #
  # Uncomment to enable authentication
  # calls:
  #   - ['authenticate', ['%env(GITHUB_USERNAME)%', '%env(GITHUB_SECRET)%', '%env(GITHUB_AUTH_METHOD)%']]

  Compwright\XHubSignature\SignerInterface:
    class: Compwright\XHubSignature\Sha256
