
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Documentation\Domain\PageDocumentContentRendererInterface:
    class: App\Documentation\Infrastructure\Content\PageDocumentContentRenderer

  App\Documentation\Domain\PageSlugGeneratorInterface:
    class: App\Documentation\Infrastructure\Content\PageSlugGenerator
