
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Documentation\Domain\PageDocumentContentRendererInterface:
    class: App\Documentation\Infrastructure\Renderer\PageDocumentContentRenderer
