
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Documentation\Infrastructure\Twig\Provider\:
    resource: '%kernel.project_dir%/app/Documentation/Infrastructure/Twig/Provider'
