
# ------------------------------------------------------------------------------
#   Blog
# ------------------------------------------------------------------------------

blog_web:
  resource:
    path: ../app/Blog/Presentation/Web/Controller/
    namespace: App\Blog\Presentation\Web\Controller
  type: attribute

blog_api:
  resource:
    path: ../app/Blog/Presentation/Api/Controller/
    namespace: App\Blog\Presentation\Api\Controller
  type: attribute
  prefix: v1
  stateless: true
  defaults:
    api: v1

# ------------------------------------------------------------------------------
#   Documentation
# ------------------------------------------------------------------------------

documentation_web:
  resource:
    path: ../app/Documentation/Presentation/Web/Controller/
    namespace: App\Documentation\Presentation\Web\Controller
  type: attribute

documentation_api:
  resource:
    path: ../app/Documentation/Presentation/Api/Controller/
    namespace: App\Documentation\Presentation\Api\Controller
  type: attribute
  prefix: v1
  stateless: true
  defaults:
    api: v1

# ------------------------------------------------------------------------------
#   Shared
# ------------------------------------------------------------------------------

web:
  resource:
    path: ../app/Shared/Presentation/Web/Controller/
    namespace: App\Shared\Presentation\Web\Controller
  type: attribute

api:
  resource:
    path: ../app/Shared/Presentation/Api/Controller/
    namespace: App\Shared\Presentation\Api\Controller
  type: attribute
  prefix: v1
  stateless: true
  defaults:
    api: v1

