web:
  resource:
    path: ../app/Presentation/Web/Controller/
    namespace: App\Presentation\Web\Controller
  type: attribute

api:
  resource:
    path: ../app/Presentation/Api/Controller/
    namespace: App\Presentation\Api\Controller
  type: attribute
  prefix: v1
  stateless: true
  defaults:
    api: v1

