
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Shared\Bus\EventBusInterface:
    class: App\Infrastructure\Bus\EventBus\PsrDispatcherEventBus

  App\Domain\Shared\Bus\CommandBusInterface:
    class: App\Infrastructure\Bus\CommandBus\SymfonyMessengerCommandBus
    arguments:
      $bus: '@command.bus'

  App\Domain\Shared\Bus\QueryBusInterface:
    class: App\Infrastructure\Bus\QueryBus\SymfonyMessengerQueryBus
    arguments:
      $bus: '@query.bus'
