
services:
  _defaults:
    autowire: true
    autoconfigure: true

  League\CommonMark\ConverterInterface:
    class: League\CommonMark\CommonMarkConverter

  # Blog

  App\Domain\Blog\ArticleContentRendererInterface:
    class: App\Infrastructure\Content\ArticleContentRenderer

  App\Domain\Blog\ArticleSlugGeneratorInterface:
    class: App\Infrastructure\Content\ArticleSlugGenerator

  App\Domain\Blog\Category\ArticleCategorySlugGeneratorInterface:
    class: App\Infrastructure\Content\ArticleCategorySlugGenerator

  # Documentation

  App\Domain\Documentation\PageDocumentContentRendererInterface:
    class: App\Infrastructure\Content\PageDocumentContentRenderer

  App\Domain\Documentation\PageSlugGeneratorInterface:
    class: App\Infrastructure\Content\PageSlugGenerator
