
services:
  _defaults:
    autowire: true
    autoconfigure: true

  League\CommonMark\ConverterInterface:
    class: League\CommonMark\CommonMarkConverter

  App\Domain\Article\Content\RendererInterface:
    class: App\Infrastructure\Renderer\ArticleMarkdownContentRenderer
