services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Documentation\Infrastructure\Persistence\Doctrine\Listener\:
    resource: '%kernel.project_dir%/app/Documentation/Infrastructure/Persistence/Doctrine/Listener'
