parameters:
  env(SYNC_NAV_PATHNAME): '.nav.json'

  app.sync.nav_pathname: '%env(SYNC_NAV_PATHNAME)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Sync\Application\UseCase\:
    resource: '%kernel.project_dir%/app/Sync/Application/UseCase'

  App\Sync\Application\UseCase\SyncVersion\SyncVersionUseCase:
    arguments:
      $navigation: '%app.sync.nav_pathname%'
