
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Documentation\Domain\Content\DocumentContentRendererInterface:
    class: App\Documentation\Infrastructure\Content\ContentRenderer\MarkdownDocumentContentRenderer
